// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandPalette
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommandPalette.9b640180-2285-4fc8-9e27-176bfc537539";
        public const string Name = "CommandPalette";
        public const string Description = @"Command Palette for VisualStudio IDE.";
        public const string Language = "en-US";
        public const string Version = "2023.1.0.2";
        public const string Author = "Lokesh Govindu";
        public const string Tags = "";
    }
}
